project_id = "kfszvzwzaevgcxwmikwk"

[functions.analyze-image]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.generate-outfit-image]
verify_jwt = false

[functions.ai-stylist]
verify_jwt = false

[functions.ai-designer]
verify_jwt = false
